version: '3.7'
services:
  nextjs:
    image: node:16
    container_name: nextjs
    volumes:
      - ./:/cirkit-blog
    ports:
      - 3000:3000
      - 5555:5555
    working_dir: /cirkit-blog
    command: bash -c "yarn upgrade && yarn dev"
    networks:
      - cirkit-blog

  mariadb:
    image: mariadb:10
    container_name: mariadb
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - cirkit-blog

volumes:
  mariadb:

networks:
  cirkit-blog:
    external: true
